# Generated by Django 5.1 on 2024-09-03 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=144)),
                ('formula', models.CharField(max_length=144)),
                ('size', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('validity', models.DateField()),
                ('classification', models.CharField(max_length=64)),
                ('control', models.CharField(choices=[('LI', 'Livre'), ('PF', 'Polícia Federal'), ('EX', 'Exército')], max_length=144)),
                ('state', models.CharField(choices=[('L', 'Líquido'), ('S', 'Sólido')], max_length=64)),
                ('opening_date', models.DateField()),
                ('incompatibility', models.ManyToManyField(blank=True, to='reagents.reagent')),
            ],
        ),
    ]
