# Generated by Django 5.1 on 2024-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='opening_date',
            field=models.DateField(null=True),
        ),
    ]
