# Generated by Django 5.1 on 2024-09-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0003_reagent_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reagent',
            options={'permissions': [('can_add', 'Can add item'), ('can_edit_item', 'Can edit item'), ('can_view_item', 'Can view item')]},
        ),
    ]
