# Generated by Django 5.1 on 2024-10-29 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0006_alter_reagent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='size',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='validity',
        ),
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.CharField(max_length=144, unique=True),
        ),
        migrations.CreateModel(
            name='ReagentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('size', models.IntegerField()),
                ('validity', models.IntegerField()),
                ('fk_reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_batch', to='reagents.reagent')),
            ],
        ),
    ]
