# Generated by Django 5.1 on 2024-11-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0009_alter_reagent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reagent',
            options={'permissions': [('can_add_reagent', 'Cadastrar Reagente'), ('can_change_reagent', 'Alterar Reagente'), ('can_delete_reagent', 'Deletar Reagente'), ('can_view_reagent', 'Ver Reagente')]},
        ),
    ]
