# Generated by Django 5.1 on 2024-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0010_alter_reagent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='control',
            field=models.CharField(choices=[('LI', 'Livre'), ('PF', 'Polícia Federal')], max_length=144),
        ),
    ]
