# Generated by Django 5.1 on 2024-09-03 16:03

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reagents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_register', models.DateField()),
                ('pdf', models.FileField(unique=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivation', models.CharField(max_length=288)),
                ('ammount', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('A', 'Adição'), ('R', 'Remoção'), ('T', 'Transferência')], max_length=64)),
                ('dt_movement', models.DateTimeField()),
                ('fk_reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_movement', to='reagents.reagent')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_movement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appoove', models.BooleanField(default=False)),
                ('dt_request', models.DateTimeField(default=datetime.date.today)),
                ('dt_response', models.DateTimeField()),
                ('fk_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_movement', to='reports.movement')),
            ],
        ),
    ]
