# Generated by Django 5.1 on 2024-09-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='dt_request',
            field=models.DateTimeField(),
        ),
    ]
