# Generated by Django 5.1 on 2024-09-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_request_dt_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='appoove',
            new_name='approved',
        ),
    ]
