# Generated by Django 5.1 on 2024-09-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_appoove_request_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='ammount',
            new_name='amount',
        ),
    ]
