# Generated by Django 5.1 on 2024-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_movement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'permissions': [('can_add_movement', 'Criar Movimentação')]},
        ),
        migrations.AddField(
            model_name='movement',
            name='validity',
            field=models.DateField(null=True),
        ),
    ]
