# Generated by Django 5.1 on 2024-10-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_movement_options_movement_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
