# Generated by Django 5.1 on 2024-10-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_movement_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='size',
        ),
    ]
