# Generated by Django 5.1 on 2024-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_request_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
