# Generated by Django 5.1 on 2024-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0011_alter_reagent_control'),
        ('reports', '0013_request_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='fk_reagentBatch',
            field=models.ManyToManyField(null=True, related_name='batch_remove', to='reagents.reagentbatch'),
        ),
    ]
