# Generated by Django 5.1 on 2024-11-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0011_alter_reagent_control'),
        ('reports', '0014_movement_fk_reagentbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='fk_reagentBatch',
            field=models.ManyToManyField(related_name='batch_remove', to='reagents.reagentbatch'),
        ),
    ]
