# Generated by Django 5.1 on 2025-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_movement_fk_reagentbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='dt_maturity',
            field=models.DateField(null=True),
        ),
    ]
